yarnPath: .yarn/releases/yarn-3.2.1.cjs
nodeLinker: pnp

packageExtensions:
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
  mongodb@*:
    dependencies:
      bson-ext: "*"
      kerberos: "*"
      snappy: "*"
      aws4: "*"
      zstd: "*"
      node-gyp: "*"
      "@mongodb-js/zstd": "*"
  debug@*:
    dependencies:
      supports-color: "*"
  styled-components@*:
    dependencies:
      react-is: "*"
