yarnPath: .yarn/releases/yarn-3.2.1.cjs
nodeLinker: node-modules

packageExtensions:
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
  debug@*:
    dependencies:
      supports-color: "*"
  styled-components@*:
    dependencies:
      react-is: "*"
