name: Run backend tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-backend:
    name: Run backend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Run backend tests
        run: yarn backend:test -- --coverage
